"""
Canonical :func:`NodeSpec.type_id` strings for engine topology and hard-rules.

**AUTO-GENERATED** — run ``python backend/scripts/gen_artifacts.py``.
The canonical set is :data:`engine.registry.NODE_SPECS` keys; import from here
instead of string literals. Do not edit by hand.
"""
from __future__ import annotations

ACTION_VALIDATOR = "ACTION_VALIDATOR"
AGGREGATOR_NODE = "AGGREGATOR_NODE"
ALERT_TRIGGER = "ALERT_TRIGGER"
COMMS_COLLECTOR = "COMMS_COLLECTOR"
CONSOLIDATED_SUMMARY = "CONSOLIDATED_SUMMARY"
DATA_HIGHLIGHTER = "DATA_HIGHLIGHTER"
DATA_REDUCER = "DATA_REDUCER"
DECISION_RULE = "DECISION_RULE"
ERROR_HANDLER = "ERROR_HANDLER"
EXECUTION_DATA_COLLECTOR = "EXECUTION_DATA_COLLECTOR"
EXTRACT_LIST = "EXTRACT_LIST"
EXTRACT_SCALAR = "EXTRACT_SCALAR"
FEATURE_ENGINE = "FEATURE_ENGINE"
GROUP_BY = "GROUP_BY"
GUARDRAIL = "GUARDRAIL"
LLM_ACTION = "LLM_ACTION"
LLM_CONTEXTUALIZER = "LLM_CONTEXTUALIZER"
LLM_CRITIC = "LLM_CRITIC"
LLM_EVALUATOR = "LLM_EVALUATOR"
LLM_PLANNER = "LLM_PLANNER"
LLM_SYNTHESIZER = "LLM_SYNTHESIZER"
LOOP_CONTROLLER = "LOOP_CONTROLLER"
MAP = "MAP"
MARKET_DATA_COLLECTOR = "MARKET_DATA_COLLECTOR"
ORACLE_DATA_COLLECTOR = "ORACLE_DATA_COLLECTOR"
PLAN_VALIDATOR = "PLAN_VALIDATOR"
REPORT_OUTPUT = "REPORT_OUTPUT"
SECTION_SUMMARY = "SECTION_SUMMARY"
SIGNAL_CALCULATOR = "SIGNAL_CALCULATOR"
STATE_MANAGER = "STATE_MANAGER"
TIME_WINDOW = "TIME_WINDOW"
TOOL_EXECUTOR = "TOOL_EXECUTOR"

__all__ = [
    "ACTION_VALIDATOR",
    "AGGREGATOR_NODE",
    "ALERT_TRIGGER",
    "COMMS_COLLECTOR",
    "CONSOLIDATED_SUMMARY",
    "DATA_HIGHLIGHTER",
    "DATA_REDUCER",
    "DECISION_RULE",
    "ERROR_HANDLER",
    "EXECUTION_DATA_COLLECTOR",
    "EXTRACT_LIST",
    "EXTRACT_SCALAR",
    "FEATURE_ENGINE",
    "GROUP_BY",
    "GUARDRAIL",
    "LLM_ACTION",
    "LLM_CONTEXTUALIZER",
    "LLM_CRITIC",
    "LLM_EVALUATOR",
    "LLM_PLANNER",
    "LLM_SYNTHESIZER",
    "LOOP_CONTROLLER",
    "MAP",
    "MARKET_DATA_COLLECTOR",
    "ORACLE_DATA_COLLECTOR",
    "PLAN_VALIDATOR",
    "REPORT_OUTPUT",
    "SECTION_SUMMARY",
    "SIGNAL_CALCULATOR",
    "STATE_MANAGER",
    "TIME_WINDOW",
    "TOOL_EXECUTOR",
]
